project:
  type: website
  resources: 
    - ".htaccess"

website:
  title: "Literary Text Mining"
  site-path: "/text-mining/"
  site-url: "https://jmclawson.net/text-mining/"
  favicon: noun-hard-hat-pink.png
  page-navigation: true
  navbar:
    logo: noun-hard-hat-smaller.png
    left:
      - href: syllabus.qmd
        text: "Syllabus"
      - href: overview.qmd
        text: "Overview"
      - href: texts.qmd
        text: "Texts"
    right:
      - text: "Units"
        menu: 
          - href: foundations/
            text: "Foundations of Text Mining with R"
          - href: features/
            text: "Mining for Simple Features"
          - href: sentiment/
            text: "Sentiment Analysis"
          - href: classification/
            text: "Text Classification"
          - href: topic/
            text: "Topic Modeling"
      - text: "Slides"
        menu: 
          - href: slides/intro-to-text-analysis.qmd
            text: Introduction to Text Analysis
      - about.qmd

  # sidebar:
  #   - id: units
  #     title: "Units"
  #     style: "docked"
  #     background: light
  #     collapse-level: 2
  #     contents: units

  page-footer: "Copyright 2022, James Clawson" 
  repo-url: https://github.com/jmclawson/text-mining
  repo-actions: [source]

format:
  html:
    theme: 
      light: [cosmo, custom.scss]
      dark: [cosmo, custom-dark.scss]
    highlight-style: "github"
    code-link: true
    css: styles.css
    toc: true
    toc-location: left
    number-sections: true
    df-print: paged
  
  revealjs:
    code-link: true
    toc: false
    theme: [moon, slides-custom.scss]
    highlight-style: dracula
    number-sections: false
    echo: true
    incremental: true
    slide-number: true
    chalkboard: true

editor: visual

