project:
  type: website
  resources: 
    - ".htaccess"
    - "tutorial-style.css"

website:
  title: "Literary Text Mining"
  site-path: "/text-mining/"
  site-url: "https://jmclawson.net/text-mining/"
  favicon: noun-hard-hat-pink.png
  page-navigation: true
  navbar:
    logo: noun-hard-hat-smaller.png
    left:
      # - href: syllabus.qmd
      #   text: "Syllabus"
      - href: overview.qmd
        text: "Overview"
      - href: texts.qmd
        text: "Texts"
    right:
      # - text: "Units"
      #   menu: 
      #     - href: foundations.qmd
      #       text: "Foundations of Text Mining with R"
      #     - href: features.qmd
      #       text: "Mining for Simple Features"
      #     - href: sentiment.qmd
      #       text: "Sentiment Analysis"
      #     - href: classification.qmd
      #       text: "Text Classification"
      #     - href: topic.qmd
      #       text: "Topic Modeling"
      - text: "Slides"
        menu: 
          - href: slides/intro-to-text-analysis.qmd
            text: Introduction to Text Analysis
      - href: about.qmd
        text: About

  # sidebar:
  #   - id: units
  #     title: "Units"
  #     style: "docked"
  #     background: light
  #     collapse-level: 2
  #     contents: units

  page-footer: "Copyright 2022, James Clawson" 
  repo-url: https://github.com/jmclawson/text-mining
  repo-actions: [source]

format:
  html:
    theme: 
      light: [cosmo, custom.scss]
      dark: [cosmo, custom-dark.scss]
    highlight-style: "github"
    code-link: true
    css: styles.css
    toc: true
    toc-location: left
    number-sections: true
    df-print: paged
    cap-location: margin

editor: visual

