---
title: "About this Site"
format:
  html:
    toc: false
    toc-location: body
    number-sections: false
---

This site was created as an open education resource for a course in literary text mining. It's built with [Quarto](https://quarto.org), an open-source publishing system that works with R, Python, and other coding languages using Pandoc. All the code can be found in the site's [GitHub repository](https://github.com/jmclawson/text-mining).

## Attributions

Hard Hat logo by Matthew Davis from [Noun Project](https://thenounproject.com/browse/icons/term/hard-hat/).

Original [transcripts](https://www.hq.nasa.gov/alsj/a13/AS13_TEC.txt) from the Apollo 13 mission are sourced from NASA's [*Apollo 13 Lunar Surface Journal*](https://www.hq.nasa.gov/alsj/a13/a13.html).

Text sets sourced from University of North Carolina's [*Documenting the American South*](https://docsouth.unc.edu/docsouthdata/) project include The Church in the Southern Black Community, First-Person Narratives of the American South, Library of Southern Literature, and North American Slave Narratives.

Title photo for "Introduction to Text Analysis" slides by [Vladislav Klapin](https://unsplash.com/@lemonvlad?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText) on [Unsplash](https://unsplash.com/s/photos/introduction?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText).

Title photo for "Distant Reading" slides by [Geoff Bryant](https://unsplash.com/fr/@hortiphoto?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText) on [Unsplash](https://unsplash.com/s/photos/distant-mountains?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText).

## Acknowledgements
