---
title: "Digital Methods for Literary Text Mining"
format:
  html:
    toc: false
    toc-location: body
    number-sections: false
---

The world is full of text. From newspapers to websites and social media, from product reviews to personal messaging, from movie scripts to novels and poetry---text is the medium of meaning. But this ubiquity doesn't make it easy to work with. Unlike numbers (which line up their digits) and tables (which pace out rows and columns), text is unstructured, ranging from ropy sentences to shorter clips, unexpectedly terse. Text surprises. It demands unique strategies for bringing structure to chaos, discovering, processing, and analyzing information buried within piles of words.

In this project-based course, students will use tools and methods of data analysis to ask questions about texts and communicate the answers. Students will learn progressively complex applications of text data mining to extract useful data from sets of documents. With special emphasis on literary study, the course will also provide opportunities to study the relevance of text mining to fields like environmental protection, public health, business, science, and security.

## Links

<!-- -   [Syllabus](syllabus.qmd) -->

-   [Overview](overview.qmd)
-   [Texts](texts.qmd)
-   [About](about.qmd)
