---
title: "Overview"
format:
  html:
    toc: false
    toc-location: body
    number-sections: false
listing: 
  - id: appendices
    contents: "appendix/*.qmd"
    template: overview.ejs
    filter-ui: false
    sort-ui: false
    table-hover: true
    sort: order
    fields: [title, description, reading-time]
    field-display-names:
      title: "Lesson"
      reading-time: "Time"
  - id: foundations
    contents: "foundations/*.qmd"
    template: overview.ejs
    filter-ui: false
    sort-ui: false
    table-hover: true
    sort: order
    fields: [title, description, reading-time]
    field-display-names:
      title: "Lesson"
      reading-time: "Time"
  - id: simplefeatures
    contents: "simple-features/*.qmd"
    template: overview.ejs
    filter-ui: false
    sort-ui: false
    table-hover: true
    sort: order
    fields: [title, description, reading-time]
    field-display-names:
      title: "Lesson"
      reading-time: "Time"
  - id: classification
    contents: "classification/*.qmd"
    template: overview.ejs
    filter-ui: false
    sort-ui: false
    table-hover: true
    sort: order
    fields: [title, description, reading-time]
    field-display-names:
      title: "Lesson"
      reading-time: "Time"
---

## I. Foundations of Text Mining with R

::: {#foundations}
:::

## II. Mining for Simple Features and Sentiment

::: {#simplefeatures}
:::

-   Once More with Feeling: Sentiment Analysis
<!-- -   NLP Transformations: Treating Words as Words -->
<!-- -   Sentiment at Large: Measuring Document-Level Sentiment -->
-   Sentiment over Time: Finding the Plot

## III. Mining for Complex Features and Correlation

-   Distinctive Words: Measuring Nuance with Tf-Idf
-   More than Words: N-grams, Phrases, and Correlation

## IV.Text Clustering and Classification

-   Multidimensional Measures: Kissing the Joy as it Flies
-   Similarity and Difference: Calculating Distance between Texts
-   Clustering and Classifying: Finding K-Nearest Neighbors
-   Visualizing High-Dimensional Data: Using Hierarchical Clusters and Principal Components Analysis

::: {#classification}
:::

## V. Topic Modeling

-   Tf-idf: Distinguishing among Documents
-   Topic Modeling: Identifying Common Threads across Documents

## VI. Appendices

::: {#appendices}
:::
